spring:
  redis:
    host: 18.182.48.242
    port: 6379
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://usa.weaxsey.org:3306/test?characterEncoding=utf-8&useSSL=false
    username: Weaxs
    password: 01weaxs06kun04_org
server:
  servlet:
    context-path: /literature
  port: 8036
mybatis:
  mapper-locations: classpath:mapper/*.xml