spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
server:
  servlet:
    context-path: /literature
  port: 8036
mybatis:
  mapper-locations: classpath:mapper/*.xml
